<?php

namespace Database\Seeders;

use App\Models\Author;
use App\Models\Faq;
use App\Models\Post;
use App\Models\PostCategory;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;

/**
 * Reads JSON files generated by scripts/generate_content.py and inserts
 * them into posts/faqs tables. Idempotent — safe to re-run.
 */
class GeneratedContentSeeder extends Seeder
{
    public function run(): void
    {
        $contentDir = database_path('content');
        if (! is_dir($contentDir)) {
            $this->command->warn("No content/ directory at $contentDir — run `python scripts/generate_content.py posts` first.");
            return;
        }

        $author = Author::firstOrCreate(
            ['slug' => 'aarambhax-editorial'],
            [
                'name' => 'Aarambhax Editorial',
                'designation' => 'Editorial Team',
                'is_active' => true,
            ],
        );

        $this->seedPosts($contentDir, $author);
        $this->seedFaqs($contentDir);
    }

    private function seedPosts(string $contentDir, Author $author): void
    {
        $postsDir = $contentDir.'/posts';
        if (! is_dir($postsDir)) {
            $this->command->info('No posts to seed.');
            return;
        }

        $count = 0;
        foreach (glob($postsDir.'/*.json') as $file) {
            $data = json_decode(file_get_contents($file), true);
            if (! $data || ! isset($data['slug'])) continue;

            $category = PostCategory::where('slug', $data['category_slug'] ?? 'new-criminal-codes')->first()
                     ?? PostCategory::firstOrCreate(
                            ['slug' => $data['category_slug'] ?? 'new-criminal-codes'],
                            ['name_en' => Str::title(str_replace('-', ' ', $data['category_slug'] ?? 'new-criminal-codes'))]
                        );

            $slug = $data['slug'];
            if (($data['language'] ?? 'en') === 'hi') {
                $slug = $slug.'-hi';
            }

            Post::updateOrCreate(
                ['slug' => $slug],
                [
                    'language'     => $data['language'] ?? 'en',
                    'category_id'  => $category->id,
                    'archetype'    => $data['archetype'] ?? 'general',
                    'title'        => $data['title'] ?? Str::title($slug),
                    'subtitle'     => $data['subtitle'] ?? null,
                    'excerpt'      => $data['excerpt'] ?? Str::limit(strip_tags($data['body'] ?? ''), 200),
                    'body'         => $data['body'] ?? '',
                    'meta_title'   => $data['meta_title'] ?? null,
                    'meta_description' => $data['meta_description'] ?? null,
                    'author_id'    => $author->id,
                    'status'       => 'published',
                    'published_at' => $data['published_at'] ?? now(),
                    'reading_time_minutes' => $data['reading_time_minutes'] ?? null,
                ],
            );
            $count++;
        }

        $this->command->info("Seeded $count post(s) from generated content.");
    }

    private function seedFaqs(string $contentDir): void
    {
        $faqsDir = $contentDir.'/faqs';
        if (! is_dir($faqsDir)) {
            $this->command->info('No FAQs to seed.');
            return;
        }

        $count = 0;
        foreach (glob($faqsDir.'/*.json') as $file) {
            $data = json_decode(file_get_contents($file), true);
            if (! $data || ! isset($data['faqs'])) continue;

            $topic = $data['topic'];
            $lang  = $data['language'] ?? 'en';

            foreach ($data['faqs'] as $i => $faq) {
                if (! isset($faq['question'], $faq['answer'])) continue;
                $slug = Str::slug(Str::limit($faq['question'], 100, ''));
                if ($lang === 'hi') $slug .= '-hi';

                Faq::updateOrCreate(
                    ['slug' => $slug],
                    [
                        'language' => $lang,
                        'question' => $faq['question'],
                        'answer'   => $faq['answer'],
                        'topic'    => $topic,
                        'related_statute_code' => $faq['related_statute_code'] ?? null,
                        'related_section_no'   => $faq['related_section_no'] ?? null,
                        'is_published' => true,
                        'is_featured'  => $i < 2,
                        'display_order' => $i,
                    ],
                );
                $count++;
            }
        }

        $this->command->info("Seeded $count FAQ(s) from generated content.");
    }
}
