<x-layouts.app
    title="Logo Concepts — Aarambhax Legal"
    description="Five creative SVG logo concepts to compare and pick from."
>
    <section class="container-page py-12">
        <header class="max-w-3xl mb-10">
            <span class="badge badge-accent mb-4">Internal — design picker</span>
            <h1 class="text-4xl sm:text-5xl font-serif font-medium mb-3" style="color: var(--fg);">
                Logo concepts
            </h1>
            <p class="text-lg" style="color: var(--fg-muted);">
                Five distinct directions generated by Gemini, each rendered fresh as SVG.
                Click any to see it at three sizes side-by-side. Note the size in bytes —
                smaller is generally better for inline / favicon use.
            </p>
        </header>

        @if(empty($concepts))
            <div class="card text-center py-12">
                <p style="color: var(--fg-muted);">
                    No concepts found. Run <code>python scripts/generate_logo_svgs.py</code> first.
                </p>
            </div>
        @else
            <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
                @foreach($concepts as $i => $c)
                    <article class="card flex flex-col">
                        <div class="flex items-center gap-2 mb-3">
                            <span class="badge badge-accent">#{{ $i + 1 }}</span>
                            <span class="text-xs font-mono" style="color: var(--fg-muted);">{{ $c['size'] }} bytes</span>
                        </div>

                        <h2 class="font-serif text-lg font-semibold mb-2" style="color: var(--fg);">
                            {{ $c['name'] }}
                        </h2>

                        {{-- Three-size preview --}}
                        <div class="rounded-lg p-6 flex items-center justify-around gap-4 mb-4" style="background: var(--surface-2); border: 1px solid var(--border);">
                            <div class="flex flex-col items-center gap-1">
                                <span class="w-6 h-6 inline-flex items-center justify-center" style="color: var(--fg);">
                                    {!! $c['svg'] !!}
                                </span>
                                <span class="text-[10px] uppercase tracking-wide" style="color: var(--fg-muted);">24px</span>
                            </div>
                            <div class="flex flex-col items-center gap-1">
                                <span class="w-12 h-12 inline-flex items-center justify-center" style="color: var(--fg);">
                                    {!! $c['svg'] !!}
                                </span>
                                <span class="text-[10px] uppercase tracking-wide" style="color: var(--fg-muted);">48px</span>
                            </div>
                            <div class="flex flex-col items-center gap-1">
                                <span class="w-24 h-24 inline-flex items-center justify-center" style="color: var(--fg);">
                                    {!! $c['svg'] !!}
                                </span>
                                <span class="text-[10px] uppercase tracking-wide" style="color: var(--fg-muted);">96px</span>
                            </div>
                        </div>

                        {{-- With wordmark preview --}}
                        <div class="rounded-lg px-4 py-3 mb-4 inline-flex items-center gap-2.5" style="background: var(--bg); border: 1px solid var(--border);">
                            <span class="w-7 h-7 inline-flex items-center justify-center" style="color: var(--fg);">
                                {!! $c['svg'] !!}
                            </span>
                            <span class="font-serif text-lg font-medium" style="color: var(--fg);">
                                Aarambha<span style="color: var(--accent);">x</span><span class="font-normal ml-1.5" style="color: var(--fg-muted);">Legal</span>
                            </span>
                        </div>

                        {{-- Inverted (dark background test) --}}
                        <div class="rounded-lg px-4 py-3 mb-4 inline-flex items-center gap-2.5" style="background: #0B1F3A; border: 1px solid var(--border);">
                            <span class="w-7 h-7 inline-flex items-center justify-center" style="color: #F8F6F0;">
                                {!! $c['svg'] !!}
                            </span>
                            <span class="font-serif text-lg font-medium" style="color: #F8F6F0;">
                                Aarambha<span style="color: #D4B062;">x</span><span class="font-normal ml-1.5" style="color: #94A3B8;">Legal</span>
                            </span>
                        </div>

                        @if(! empty($c['direction']))
                            <p class="text-xs flex-1 mb-3" style="color: var(--fg-muted);">
                                <strong>Brief:</strong> {{ \Illuminate\Support\Str::limit($c['direction'], 200) }}
                            </p>
                        @endif

                        <div class="flex items-center gap-2 text-xs" style="color: var(--fg-muted);">
                            <a href="{{ asset($c['svg_path']) }}" target="_blank" style="color: var(--link);">View raw SVG</a>
                            <span>·</span>
                            <code class="font-mono" style="font-size: 11px;">{{ $c['id'] }}</code>
                        </div>
                    </article>
                @endforeach
            </div>

            <div class="mt-12 card max-w-2xl mx-auto" style="background: var(--surface-2);">
                <h2 class="font-serif text-xl font-semibold mb-2" style="color: var(--fg);">How to apply your pick</h2>
                <ol class="text-sm space-y-2" style="color: var(--fg-muted);">
                    <li>1. Choose the concept you like best.</li>
                    <li>2. Note its filename (e.g. <code>concept-3-quill-stroke.svg</code>).</li>
                    <li>3. Tell me the filename and I'll wire it into the <code>&lt;x-logo&gt;</code> Blade component everywhere.</li>
                </ol>
            </div>
        @endif
    </section>
</x-layouts.app>
