<x-layouts.app
    title="Sample Drafts — Aarambhax Legal"
    description="Real drafts generated by Aarambhax. HC writs in English, district pleadings in Hindi, revenue applications with khasra/khata structure."
>
    <section class="container-page py-12">
        <header class="mb-10 max-w-3xl">
            <span class="badge badge-accent mb-4">Real output, not promises</span>
            <h1 class="text-4xl sm:text-5xl font-serif font-medium leading-tight mb-4" style="color: var(--fg);">
                See what Aarambhax actually produces
            </h1>
            <p class="text-lg" style="color: var(--fg-muted);">
                Three real drafts across the forums Aarambhax supports. Click any sample to see the full text — including
                cause-titles, grounds, and citations.
            </p>
        </header>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
            @foreach($samples as $s)
                <a href="{{ route('sample-drafts.show', $s['slug']) }}" class="card block hover:bg-surface2 transition-colors h-full" style="text-decoration: none; color: inherit;">
                    <div class="flex items-center gap-2 mb-3 flex-wrap">
                        <span class="badge badge-accent">{{ $s['forum'] }}</span>
                        <span class="badge" style="background: color-mix(in srgb, var(--link) 18%, transparent); color: var(--link);">{{ $s['language'] }}</span>
                    </div>
                    <h2 class="font-serif text-xl font-semibold mb-2 leading-tight" style="color: var(--fg);">{{ $s['title'] }}</h2>
                    <p class="text-sm mb-4" style="color: var(--fg-muted);">{{ $s['subtitle'] }}</p>
                    <div class="text-xs space-y-1 pt-3 border-t" style="border-color: var(--border); color: var(--fg-muted);">
                        <p><strong>Parties:</strong> {{ $s['parties'] }}</p>
                        <p><strong>Sections:</strong> {{ implode(', ', $s['sections']) }}</p>
                    </div>
                    <p class="mt-4 text-sm font-medium" style="color: var(--accent);">Read full draft →</p>
                </a>
            @endforeach
        </div>

        <div class="card mt-12 max-w-2xl mx-auto text-center" style="background: var(--surface-2); border-color: var(--accent);">
            <h2 class="font-serif text-2xl font-semibold mb-2" style="color: var(--fg);">Generate yours.</h2>
            <p class="text-sm mb-6" style="color: var(--fg-muted);">
                Tell Aarambhax your case facts. Get a court-ready draft in 30 seconds, with verified citations.
            </p>
            <div class="flex justify-center gap-3 flex-wrap">
                <a href="{{ route('register') }}" class="btn btn-primary">Try free — beta</a>
                <a href="{{ route('verifier.show') }}" class="btn btn-secondary">Try free Verifier</a>
            </div>
        </div>
    </section>
</x-layouts.app>
